### ISSUE TITLE
backtrace in crawler

### ISSUE THREAD

**Issue by flepied** [morucci/monocle#96]
```Python
2020-04-17 09:37:51,285 - monocle.github.pullrequest - kubernetes/.* - INFO - Running request {'org': 'kubernetes', 'repository': None, 'updated_since': '2000-01-01', 'after': 'after: "Y3Vyc29yOjc3NQ=="', 'created_before': '2020-02-19T17:43:30Z', 'total_prs_count': 117727, 'size': 25, 'scope': 'org:kubernetes'}
Exception in thread kubernetes/.*:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/site-packages/monocle-0.1.0-py3.7.egg/monocle/crawler.py", line 79, in run
    self.run_step()
  File "/usr/local/lib/python3.7/site-packages/monocle-0.1.0-py3.7.egg/monocle/crawler.py", line 71, in run_step
    prs = self.prf.get(updated_since)
  File "/usr/local/lib/python3.7/site-packages/monocle-0.1.0-py3.7.egg/monocle/github/pullrequest.py", line 226, in get
    hnp = self._getPage(kwargs, prs)
  File "/usr/local/lib/python3.7/site-packages/monocle-0.1.0-py3.7.egg/monocle/github/pullrequest.py", line 198, in _getPage
    for pr in data['data']['search']['edges']:
KeyError: 'data'
```

**Comment by flepied** [comment]
fixed in https://github.com/morucci/monocle/pull/102
